### ISSUE TITLE
Numbers and booleans in merges don't rendered as strings

### ISSUE THREAD

**Issue by fbjorn** [Lieturd/project-template#14]
This leads to errors while `kubectl apply`:
`for: "<>/01-config.yaml": unrecognized type: string`
`for: "<>/01-config.yaml": cannot convert int64 to string`

Test case to reproduce
```python
CONFIG_DATA = """
apiVersion: v1
data:
  debug: 'False'
  number: '0'
kind: ConfigMap
metadata:
  name: app-config
"""

CONFIG_DATA_OVERRIDES = """
data:
  debug: 'True'
  number: '1'
"""

CONFIG_DATA_EXPECTED = """
apiVersion: v1
data:
  debug: 'True'
  number: '1'
kind: ConfigMap
metadata:
  name: app-config
"""


def test_merge_string_bools_and_numbers():
    docs = list(yaml.load_all(StringIO(CONFIG_DATA), yaml.Loader))
    overrides = list(yaml.load_all(StringIO(CONFIG_DATA_OVERRIDES), yaml.BaseLoader))
    expected = list(yaml.load_all(StringIO(CONFIG_DATA_EXPECTED), yaml.Loader))

    merged = merge_docs(docs, overrides)
    for i, merged_doc in enumerate(merged):
        expected_doc = expected[i]

        merged_json = json.dumps(merged_doc, **JSON_FORMAT)
        expected_json = json.dumps(expected_doc, **JSON_FORMAT)

        print(f"Doc {i + 1} expected: {expected_json}")
        print(f"Doc {i + 1} actual  : {merged_json}")

        assert merged_json == expected_json
```

**Comment by fbjorn** [comment]
I workarounded this temporarily by force conversion all the values to strings, because there were problems with [applying configurations ](https://medium.com/@ismailyenigul/kubernetes-configmap-and-cannot-convert-int64-to-string-error-ebf48fa1cd28)
however, some of the values must be numbers, like `replicas` in the Deployment. Need to investigate deeper on this topic..

**Comment by lietu** [comment]
If `replicas` comes as the last step from the settings.py then that specific issue should be worked around as well .. anyway, yes, we need to preserve the correct data types here, that is very important.

**Comment by soderluk** [comment]
PR: #23 should fix this as well.

**Comment by lietu** [comment]
Assuming fixed - reopen if still a problem.
